---
deployment:
  tasks:
    - export DEPLOYPATH=/VashonG/nft-gated-website-main/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
